articles/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name = 'acticles'

urlpatterns = [
    path('' , views.articles_list , name = 'listOfArticles'),
    path('<slug>' , views.article_detail , name='detail'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , views.home),
    path('about/', views.about),
    path('articles/', include('articles.urls')),
    path('accounts/' , include('accounts.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from email.policy import default
from django.db import models
from matplotlib import image
from matplotlib.pyplot import title

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug  = models.SlugField()
    body  = models.TextField()
    date  = models.DateTimeField(auto_now_add=True)
    img = models.ImageField(default='default.jpg' , blank = True)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + ' ...'

accounts/views.py
from django.shortcuts import render , redirect
from django.contrib.auth.forms import UserCreationForm , AuthenticationForm

def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid() :
            form.save()
            return redirect('acticles:listOfArticles')

    else:
        form = UserCreationForm()
    return render(request , 'accounts/signup.html',{'form' : form})


def login_view(request):
    if request.method == "POST":
        pass
    else:
        form = AuthenticationForm()
    return render(request , 'accounts/login.html' , {'form':form})

articles/views.py
from ast import arg
from django.shortcuts import render , HttpResponse
from tomlkit import date
from . import models

# Create your views here.

def articles_list(request):
    articles =  models.Article.objects.all().order_by('-date')
    args = {'articles':articles}
    return render(request,'articles/articles_list.html',args)

def article_detail(request,slug):
    # return HttpResponse(slug)
    article = models.Article.objects.get(slug=slug)
    args = {'article' : article}
    return render(request , 'articles/article_detail.html' , args)

blog/views.py
import re
from django.shortcuts import render
from django.shortcuts import HttpResponse

def home(request):
    #return HttpResponse('hey there! Im django')
    return render(request,'home.html')

def about(request):
    #return HttpResponse('this is about page')
    return render(request,'about.html')

articles/templates/articles/articles_list.html
{% extends "base.html" %}
{% block title %}
    Article
{% endblock title %}

{% block content %}
<h1>Articles</h1>
<div class="container">
    {% for article in articles %}
        <h2>
            <a href="{% url 'acticles:detail' slug=article.slug %}">{{ article.title }}</a>
        </h2>
        <p>
            {{ article.snippet }}
        </p>
        <p>
            {{ article.date }}
        </p>
    {% endfor %}
</div>

{% endblock content %}
       

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
</head>
<body>
    <h1>About Page</h1>
    <p>
        we love django.
    </p>
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    {# <link rel="stylesheet" href="/static/styles.css">#}
    <link rel="stylesheet" href="{% static 'styles.css' %}"/>
    
    <title>
        {% block title %}

        {% endblock title %}
    </title>
    </head>
    <body>
        <h2>
            <a href="{% url 'acticles:listOfArticles' %}">LOGO</a>
        </h2>
        <div class="wrapper">
            {% block content %}

            {% endblock content %}
        </div>
        

    </body>
    </html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <h1>Hey There!</h1>
    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Officia, voluptatum natus similique assumenda harum minima perspiciatis qui dolorum ipsa atque, ex rerum fugiat consectetur nulla facilis dolorem? Reprehenderit, illo debitis!</p>
    
</body>
</html>